Change type node into node_type. Removing of parent_key
g2p/mirage-storage pull request #44
Opened 2019-02-12 14:58 UTC by fondation451

type node is rewritten into node_ty.

node_ty is either a Root with a depth or a Child with a parent_key.

it allows us to remove the parent_key

2019-02-12 15:44 UTC, g2p requested changes
Fusing the parent_key is good.
The rdepth / height should stay outside of this type.
I'm not sure on the new name.
Either pick something like node_meta or leave it for a renaming pass.

2019-02-19 14:54 UTC, pascutto commented
I removed the depth from the type, though I left the name unchanged, maybe we should think of a better name during the renaming pass, as you suggested.

2019-02-19 16:48 UTC, g2p approved these changes

2019-02-19 16:49 UTC, g2p commented
Since the PR already introduced new names, I changed it to meta : node_meta.
Let's merge this once the CI passes.

2019-02-19 18:21 UTC, merged